"""added product discount and product discount payment method relationships

Revision ID: 8879ae9c21b1
Revises: 23533f7776f4
Create Date: 2021-12-09 13:35:49.959321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8879ae9c21b1'
down_revision = '23533f7776f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'payment_methods', ['payment_form_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
