"""explict relationship order-address order-payment-method

Revision ID: 923722242a59
Revises: 039cbf6274dd
Create Date: 2021-12-08 11:10:15.617622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923722242a59'
down_revision = '039cbf6274dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
